spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: zerone
    password: 980324
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true